/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SketchSupreme (https://sketchfab.com/sketchsupreme)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-man-fortnite-chapter-2-season-1-bp-skin-d4dcc913d1ac4982a44573acdf138c55
Title: Spider-Man | Fortnite Chapter 2 Season 1 BP Skin
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations  } from '@react-three/drei'

const MOdel=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '/spiderman.glb'
  )
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3bd38f4236234d35898f64206f3b32d3fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="M_MED_Parallel_Comic_LOD0ao"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_158"
                      geometry={nodes.Object_158.geometry}
                      material={materials.M_MED_Parallel_Comic_Body}
                      skeleton={nodes.Object_158.skeleton}
                    />
                    <skinnedMesh
                      name="Object_159"
                      geometry={nodes.Object_159.geometry}
                      material={materials.M_MED_Parallel_Comic_Head}
                      skeleton={nodes.Object_159.skeleton}
                    />
                    <group name="Object_157" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group
                  name="M_MED_Parallel_Comic_LOD0mo"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman.glb');
export default MOdel;